EXECUTABLE       := fft
CFILES           := src/complex.cpp src/fft.cpp src/fourier.cpp
INCLUDE          := -I../common/src
RUN_COMMAND      := ./scripts/run.sh
VALIDATE_COMMAND := ./scripts/validate.sh

include ../common/makefiles/common.mk
