EXECUTABLE := fdtd2d.exe
CFILES := fdtd2d.c
CLFILE := fdtd2d.cl
PATH_TO_UTILS := ../utilities

TAFFO_EXEC_OPTS   ?=-Xdta -bufferid-import -Xdta taffo_kern_logs/bufferid.yaml
TAFFO_KERN_OPTS   ?=-Xdta -bufferid-export -Xdta taffo_kern_logs/bufferid.yaml

include ${PATH_TO_UTILS}/common.mk
