EXECUTABLE       := sobel
CFILES           := src/convolution.cpp src/rgb_image.cpp src/sobel.cpp
INCLUDE          := -I../common/src
RUN_COMMAND      := ./scripts/run.sh
VALIDATE_COMMAND := ./scripts/validate.sh

include ../common/makefiles/common.mk
