EXECUTABLE       := jmeint
CFILES           := src/jmeint.cpp src/tritri.cpp
INCLUDE          := -I../common/src
RUN_COMMAND      := ./scripts/run.sh
VALIDATE_COMMAND := ./scripts/validate.sh

include ../common/makefiles/common.mk
