EXECUTABLE       := inversek2j
CFILES           := src/inversek2j.cpp src/kinematics.cpp
INCLUDE          := -I../common/src
RUN_COMMAND      := ./scripts/run.sh
VALIDATE_COMMAND := ./scripts/validate.sh

include ../common/makefiles/common.mk
