EXECUTABLE       := kmeans
CFILES           := src/distance.cpp src/kmeans.cpp src/rgbimage.cpp src/segmentation.cpp
INCLUDE          := -I../common/src
RUN_COMMAND      := ./scripts/run.sh
VALIDATE_COMMAND := ./scripts/validate.sh

include ../common/makefiles/common.mk
